=== NTUT-NPC/tattoo/build_config/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TattooBuildConfig",
  "type": "object",
  "required": [
    "name",
    "flavor",
    "app_name",
    "android",
    "ios",
    "firebase"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "enum": [
        "development",
        "production",
        "dev",
        "prod"
      ]
    },
    "flavor": {
      "type": "string",
      "enum": [
        "dev",
        "prod"
      ]
    },
    "app_name": {
      "type": "string"
    },
    "ENV": {
      "type": "string"
    },
    "FLAVOR": {
      "type": "string"
    },
    "APP_NAME": {
      "type": "string"
    },
    "APP_CONFIG_NAME": {
      "type": "string"
    },
    "APP_CONFIG_ICON_NAME": {
      "type": "string"
    },
    "ANDROID_APPLICATION_ID": {
      "type": "string"
    },
    "ANDROID_APP_LABEL": {
      "type": "string"
    },
    "ANDROID_RES_DIR": {
      "type": "string"
    },
    "ANDROID_FIREBASE_CONFIG_PATH": {
      "type": "string"
    },
    "IOS_BUNDLE_IDENTIFIER": {
      "type": "string"
    },
    "IOS_BUNDLE_DISPLAY_NAME": {
      "type": "string"
    },
    "IOS_APP_ICON_NAME": {
      "type": "string"
    },
    "IOS_FIREBASE_CONFIG_PATH": {
      "type": "string"
    },
    "android": {
      "type": "object",
      "required": [
        "application_id",
        "app_name",
        "icon",
        "google_services_path"
      ],
      "properties": {
        "application_id": {
          "type": "string"
        },
        "app_name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "res_dir": {
          "type": "string"
        },
        "google_services_path": {
          "type": "string"
        }
      }
    },
    "ios": {
      "type": "object",
      "required": [
        "bundle_identifier",
        "bundle_display_name",
        "app_icon_name",
        "google_service_info_path"
      ],
      "properties": {
        "bundle_identifier": {
          "type": "string"
        },
        "bundle_display_name": {
          "type": "string"
        },
        "app_icon_name": {
          "type": "string"
        },
        "google_service_info_path": {
          "type": "string"
        }
      }
    },
    "firebase": {
      "type": "object",
      "required": [
        "project_id",
        "storage_bucket"
      ],
      "properties": {
        "project_id": {
          "type": "string"
        },
        "storage_bucket": {
          "type": "string"
        },
        "android": {
          "type": "object",
          "properties": {
            "package_name": {
              "type": "string"
            },
            "app_id": {
              "type": "string"
            }
          }
        },
        "ios": {
          "type": "object",
          "properties": {
            "bundle_id": {
              "type": "string"
            },
            "app_id": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== NTUT-NPC/tattoo/build_config/production.json
{
  "$schema": "./schema.json",
  "name": "production",
  "flavor": "prod",
  "app_name": "TAT",
  "ENV": "production",
  "FLAVOR": "prod",
  "APP_NAME": "TAT",
  "APP_CONFIG_NAME": "TAT",
  "APP_CONFIG_ICON_NAME": "AppIcon",
  "ANDROID_APPLICATION_ID": "club.ntut.npc.tat",
  "ANDROID_APP_LABEL": "TAT",
  "ANDROID_RES_DIR": "android/app/src/main/res",
  "ANDROID_FIREBASE_CONFIG_PATH": "android/app/google-services.json",
  "IOS_BUNDLE_IDENTIFIER": "com.ntut.tatflutter",
  "IOS_BUNDLE_DISPLAY_NAME": "TAT",
  "IOS_APP_ICON_NAME": "AppIcon",
  "IOS_FIREBASE_CONFIG_PATH": "ios/Runner/GoogleService-Info.plist",
  "android": {
    "application_id": "club.ntut.npc.tat",
    "app_name": "TAT",
    "icon": "ic_launcher",
    "res_dir": "android/app/src/main/res",
    "google_services_path": "android/app/google-services.json"
  },
  "ios": {
    "bundle_identifier": "com.ntut.tatflutter",
    "bundle_display_name": "TAT",
    "app_icon_name": "AppIcon",
    "google_service_info_path": "ios/Runner/GoogleService-Info.plist"
  },
  "firebase": {
    "project_id": "npc-tattoo-prod",
    "storage_bucket": "npc-tattoo-prod.firebasestorage.app",
    "android": {
      "package_name": "club.ntut.npc.tat",
      "app_id": "1:596630117465:android:9d4275579e011f039f6548"
    },
    "ios": {
      "bundle_id": "com.ntut.tatflutter",
      "app_id": "1:596630117465:ios:afd1697a77bcb95f9f6548"
    }
  }
}

=== NTUT-NPC/tattoo/build_config/dev.json
{
  "$schema": "./schema.json",
  "name": "development",
  "flavor": "dev",
  "app_name": "Tattoo",
  "ENV": "development",
  "FLAVOR": "dev",
  "APP_NAME": "Tattoo",
  "APP_CONFIG_NAME": "Tattoo",
  "APP_CONFIG_ICON_NAME": "AppIcon-dev",
  "ANDROID_APPLICATION_ID": "club.ntut.tattoo",
  "ANDROID_APP_LABEL": "Tattoo",
  "ANDROID_RES_DIR": "android/app/src/dev/res",
  "ANDROID_FIREBASE_CONFIG_PATH": "android/app/google-services.json",
  "IOS_BUNDLE_IDENTIFIER": "club.ntut.tattoo",
  "IOS_BUNDLE_DISPLAY_NAME": "Tattoo",
  "IOS_APP_ICON_NAME": "AppIcon-dev",
  "IOS_FIREBASE_CONFIG_PATH": "ios/Runner/GoogleService-Info.plist",
  "android": {
    "application_id": "club.ntut.tattoo",
    "app_name": "Tattoo",
    "icon": "ic_launcher",
    "res_dir": "android/app/src/dev/res",
    "google_services_path": "android/app/google-services.json"
  },
  "ios": {
    "bundle_identifier": "club.ntut.tattoo",
    "bundle_display_name": "Tattoo",
    "app_icon_name": "AppIcon-dev",
    "google_service_info_path": "ios/Runner/GoogleService-Info.plist"
  },
  "firebase": {
    "project_id": "npc-tattoo",
    "storage_bucket": "npc-tattoo.firebasestorage.app",
    "android": {
      "package_name": "club.ntut.tattoo",
      "app_id": "1:838220085712:android:a85cf2541699925c3be1d5"
    },
    "ios": {
      "bundle_id": "club.ntut.tattoo",
      "app_id": "1:838220085712:ios:d5b7636cdc72fd603be1d5"
    }
  }
}

=== NTUT-NPC/tattoo/build_config/prod.json
{
  "$schema": "./schema.json",
  "name": "production",
  "flavor": "prod",
  "app_name": "TAT",
  "android": {
    "application_id": "club.ntut.npc.tat",
    "app_name": "TAT",
    "icon": "ic_launcher",
    "res_dir": "android/app/src/main/res",
    "google_services_path": "android/app/google-services.json"
  },
  "ios": {
    "bundle_identifier": "com.npc.tatFlutter",
    "bundle_display_name": "TAT",
    "app_icon_name": "AppIcon",
    "google_service_info_path": "ios/Runner/GoogleService-Info.plist"
  },
  "firebase": {
    "project_id": "npc-tattoo-prod",
    "storage_bucket": "npc-tattoo-prod.firebasestorage.app",
    "android": {
      "package_name": "club.ntut.npc.tat",
      "app_id": "1:596630117465:android:9d4275579e011f039f6548"
    },
    "ios": {
      "bundle_id": "com.npc.tatFlutter",
      "app_id": "1:596630117465:ios:afd1697a77bcb95f9f6548"
    }
  }
}
